import { Area } from './area';
import { Cargo } from './cargo';
import { TipoContrato } from './tipo-contrato';
import { EstadoTrabajador } from './estado-trabajador';
import { Empleador } from './empleador';
import { RegimenLaboral } from './regimen-laboral';
import { Ocupacion } from './ocupacion';
import { JornadaLaboral } from './jornada-laboral';
import { NivelEducativo } from './nivel-educativo';
import { RegimenSalud } from './regimen-salud';
import { RegimenPensiones } from './regimen-pensiones';
import { Afp } from './afp';
import { Ubigeo } from './ubigeo';
import { TipoDocumento } from './tipo-documento';

export interface Trabajador {
  id_trabajador?: number;
  paterno?: string;
  materno?: string;
  primer?: string;
  segundo?: string;
  id_tipo_documento?: number;
  numero_documento?: string;
  fecha_nacimiento?: string;
  ruc?: string;
  direccion?: string;
  referencia?: string;
  id_ubigeo?: number;
  telefono?: string;
  celular?: string;
  correo?: string;
  id_empleador?: number;
  id_regimen_laboral?: number;
  id_ocupacion?: number;
  id_tipo_contrato?: number;
  id_cargo?: number;
  es_jefe?: number;
  id_jornada_laboral?: number;
  id_estado_trabajador?: number;
  fecha_estado?: string;
  id_nivel_educativo?: number;
  id_regimen_salud?: number;
  id_regimen_pensiones?: number;
  id_afp?: number;
  cuspp?: string;
  es_discapacitado?: number;
  es_sindicalizado?: number;
  fecha_ingreso?: string;
  fecha_egreso?: string;
  id_motivo_baja?: number;
  fecha_baja?: string;
  id_contrato?: number;
  aprueba_solicitudes?: number;
  saldo_inicial_vacaciones?: string;
  id_user?: number;
  created_at?: string;
  updated_at?: string;

  // Relaciones
  area?: Area;
  cargo?: Cargo;
  tipo_contrato?: TipoContrato;
  estado_trabajador?: EstadoTrabajador;
  empleador?: Empleador;
  regimen_laboral?: RegimenLaboral;
  ocupacion?: Ocupacion;
  jornada_laboral?: JornadaLaboral;
  nivel_educativo?: NivelEducativo;
  regimen_salud?: RegimenSalud;
  regimen_pensiones?: RegimenPensiones;
  afp?: Afp;
  ubigeo?: Ubigeo;
  tipo_documento?: TipoDocumento;
}
